# Exercises

In [1]:
import numpy as np

a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

# 1. How many negative numbers are there?

# Created negative_num variable and assigned the sum method to sum all numbers in the array that are less than zero.
negative_nums = np.sum(a < 0)
print('Number of negative values = ', negative_nums, '\n')


# 2. How many positive numbers are there?

# Created a positive_num variable and assigned the sum method to sum all numbers in the array that are greater than zero.
# 0 is neither a positive or a negative so its value is non-inclusive
positive_nums = np.sum(a > 0)
print('Number of positive values = ', positive_nums, '\n')


# 3. How many even positive numbers are there?

# Created a even_positive_nums variable and assigned the sum method to sum all numbers in the array greater than 0 and divisible by 2 using the modulo operator.
# both conditions are applied usinf the '&' character after grouping each operation.
even_positive_nums = np.sum((a > 0) & (a % 2 == 0))
print('Number of even and postive numbers = ', even_positive_nums, '\n')

# 4. If you were to add 3 to each data point, how many positive numbers would there be?

# assigned new variable with array values plus three and called back with a comparison to 0 and suffixed the sum() method using the '.' syntax
array_with_three_added = a + 3
print('Number of positive numbers with 3 added = ', (array_with_three_added > 0).sum(), '\n')

# 5. If you squared each number, what would the new mean and standard deviation be?

# squared array values and then printed mean and standard deviation values using the numpy methods
a ** 2
print('Mean an standard deviation of array values squared:\n\n', 'Mean:', a.mean(), '\n\n STD:', a.std())


# 6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

# assigned variable centered_a to array subtracted by the array mean and printed the new array values by calling variable name
centered_a = a - a.mean()
print('\nCentered data:', centered_a, '\n')


# 7. Calculate the z-score for each data point. Recall that the z-score is given by:

# z score is calculated by subtracting the array values the mean of arrays then divided by the standard deviation values of the array. 
# z_score was assigned to the calculation and returned when variable was called.
mean = np.mean(a)
std = np.std(a)

z_scores = (a - mean) / std
print("Z-scores:", z_scores)

Number of negative values =  4 

Number of positive values =  5 

Number of even and postive numbers =  3 

Number of positive numbers with 3 added =  10 

Mean an standard deviation of array values squared:

 Mean: 3.0 

 STD: 8.06225774829855

Centered data: [  1.   7.   9.  20.  -5.  -4.  -3.  -3.  -3.  -9.   0. -10.] 

Z-scores: [ 0.12403473  0.86824314  1.11631261  2.48069469 -0.62017367 -0.49613894
 -0.3721042  -0.3721042  -0.3721042  -1.11631261  0.         -1.24034735]


# Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.


In [2]:
import numpy as np
# Life w/o numpy to life with numpy

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Created a variable called sum_of_a to hold the sum of all the numbers in above list

# Sum of all numbers
sum_of_a = sum(a)
print("Sum of a:", sum_of_a)

# Exercise 2 - Created a variable named min_of_a to hold the minimum of all the numbers in the above list

# Minimum number
min_of_a = min(a)
print("\nMinimum of a:", min_of_a)


# Exercise 3 - Created a variable named max_of_a to hold the max number of all the numbers in the above list

# Maximum number
max_of_a = max(a)
print("\nMaximum of a:", max_of_a)

# Exercise 4 - Created a variable named mean_of_a to hold the average of all the numbers in the above list

# Mean (average) of all numbers
mean_of_a = sum(a) / len(a)
print("\nMean of a:", mean_of_a)

# Exercise 5 - Created a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

# Product of all numbers
product_of_a = 1
for num in a:
    product_of_a *= num
print("\nProduct of a:", product_of_a)

# Exercise 6 - Created a variable named squares_of_a. to hold each number in a squared like [1, 4, 9, 16, 25...]

# Squares of all numbers
squares_of_a = [num ** 2 for num in a]
print("\nSquares of a:", squares_of_a)

# Exercise 7 - Created a variable named odds_in_a. to hold only the odd numbers

# Odd numbers
odds_in_a = [num for num in a if num % 2 != 0]
print("\nOdd numbers in a:", odds_in_a)

# Exercise 8 - Make a variable named evens_in_a. Should hold only the evens.

# Even numbers
evens_in_a = [num for num in a if num % 2 == 0]
print("\nEven numbers in a:", evens_in_a)


Sum of a: 55

Minimum of a: 1

Maximum of a: 10

Mean of a: 5.5

Product of a: 3628800

Squares of a: [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

Odd numbers in a: [1, 3, 5, 7, 9]

Even numbers in a: [2, 4, 6, 8, 10]


## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...

## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

In [65]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
# sum_of_b = 0
# for row in b:
#     sum_of_b += sum(row)

sum_of_b = np.sum(b)
print('Sum of b: ', sum_of_b)

# Exercise 2 - refactor the following to use numpy. 
# min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])

min_of_b = np.min(b)
print('\nMinimum of b: ', min_of_b)

# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
# max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

max_of_b = np.max(b)
print('\nMax of b: ', max_of_b)


# Exercise 4 - refactor the following using numpy to find the mean of b
# mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

mean_of_b = np.mean(b)
print('\nMean of b: ', mean_of_b)

# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
# product_of_b = 1
# for row in b:
#     for number in row:
#         product_of_b *= number

product_of_b = np.product(b)
print('\nProduct of b: ', product_of_b)

# Exercise 6 - refactor the following to use numpy to find the list of squares 
# squares_of_b = []
# for row in b:
#     for number in row:
#         squares_of_b.append(number**2)

squares_of_b = np.square(b)
print('\nSquares of b: \n\n', squares_of_b)


# Exercise 7 - refactor using numpy to determine the odds_in_b
# odds_in_b = []
# for row in b:
#     for number in row:
#         if(number % 2 != 0):
#             odds_in_b.append(number)

b_arr = np.array([b])
odds_in_b = b_arr[b_arr % 2 != 0]
print('\nOdds: ', odds_in_b)

# Exercise 8 - refactor the following to use numpy to filter only the even numbers
# evens_in_b = []
# for row in b:
#     for number in row:
#         if(number % 2 == 0):
#             evens_in_b.append(number)

b_arr = np.array([b])
even_in_b = b_arr[b_arr % 2 == 0]
print('\nEvens: ', even_in_b)

# Exercise 9 - print out the shape of the array b.
b_shape= np.shape(b)
print('\nb Shape: ', b_shape)

# Exercise 10 - transpose the array b.

b_transposed = np.transpose(b)
print('\nb Transopsed: \n\n', b_transposed)

# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

b_reshape = np.reshape(b,(1, 6))
print('\nb Reshape: ', b_reshape)

# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

b_vertical_list = np.reshape(b,(6, 1))
print('\nb Vertical list: \n\n', b_vertical_list)


Sum of b:  33

Minimum of b:  3

Max of b:  8

Mean of b:  5.5

Product of b:  20160

Squares of b: 

 [[ 9 16 25]
 [36 49 64]]

Odds:  [3 5 7]

Evens:  [4 6 8]

b Shape:  (2, 3)

b Transopsed: 

 [[3 6]
 [4 7]
 [5 8]]

b Reshape:  [[3 4 5 6 7 8]]

b Vertical list: 

 [[3]
 [4]
 [5]
 [6]
 [7]
 [8]]


## Setup 3

In [66]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

c_arr = np.array([c])
c_arr

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.

# Exercise 2 - Determine the standard deviation of c.

# Exercise 3 - Determine the variance of c.

# Exercise 4 - Print out the shape of the array c

# Exercise 5 - Transpose c and print out transposed result.

# Exercise 6 - Get the dot product of the array c with c. 

# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

## Setup 4

In [5]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

# Exercise 1 - Find the sine of all the numbers in d

# Exercise 2 - Find the cosine of all the numbers in d

# Exercise 3 - Find the tangent of all the numbers in d

# Exercise 4 - Find all the negative numbers in d

# Exercise 5 - Find all the positive numbers in d

# Exercise 6 - Return an array of only the unique numbers in d.

# Exercise 7 - Determine how many unique numbers there are in d.

# Exercise 8 - Print out the shape of d.

# Exercise 9 - Transpose and then print out the shape of d.

# Exercise 10 - Reshape d into an array of 9 x 2